name: SkySys
version: '1.0.0'
main: com.karpen.skySys.SkySys
api-version: '1.21'
commands:
  website:
    usage: /website
    description: Наш вебсайт
  check:
    usage: /check
    description: Вызвать игрока на проверку
    permission: karpen.skySys.check
    permission-message: У вас недостаточно прав
  check-stop:
    usage: /check-stop
    description: Остановить проверку
    permission: karpen.skySys.check
    permission-message: У вас недостаточно прав
