name: SkySys
version: '1.2'
main: com.karpen.skySys.SkySys
api-version: '1.21'
commands:
  check:
    usage: /check
    description: Вызвать игрока на проверку
    permission: karpen.skySys.check
    permission-message: У вас недостаточно прав
  check-stop:
    usage: /check-stop
    description: Остановить проверку
    permission: karpen.skySys.check
    permission-message: У вас недостаточно прав
  size:
    usage: /size < min | normal | big>
    description: Изменить размер игрока
    permission: karpen.skySys.size
    permission-message: У вас недостаточно прав
  vrestart:
    usage: /vrestart
    description: Перезагружает сервер с предупреждением
    permission: karpen.skySys.vrestart
    permission-message: У вас недостаточно прав
